# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"

install:
    - pip install flask
    - pip install -U .

script: nosetests
